#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JustEatDemo.Resource", IsApplication=true)]

namespace JustEatDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int rotate = 2131034112;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int maxRating = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rating = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060002
			public const int accent = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int flat_action_button_pressed = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int primary = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int primary_dark = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int progress_dialog_background = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int raised_button_normal = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int raised_button_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070009
			public const int default_margin = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int edit_text_cursor_size = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int flat_action_button_corner_radius = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int flat_action_button_size = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int insert_location_objects_height = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int insert_location_objects_width = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int rating_bar_space_between_stars = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int rating_bar_star_size = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int rating_bar_width = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int restaurant_logo_default_size = 2131165192;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int edit_text_cursor = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flat_action_button_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flat_action_button_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_empty_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_star_empty = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_star_full = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_star_half = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int insert_location_area_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int insert_location_find_takeaways = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0009
			public const int cousine = 2131427337;
			
			// aapt resource value: 0x7f0b0003
			public const int delete_postcode = 2131427331;
			
			// aapt resource value: 0x7f0b0005
			public const int find_takeaways = 2131427333;
			
			// aapt resource value: 0x7f0b0001
			public const int insert_location = 2131427329;
			
			// aapt resource value: 0x7f0b0006
			public const int list = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int logo = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int name = 2131427336;
			
			// aapt resource value: 0x7f0b0004
			public const int postcode = 2131427332;
			
			// aapt resource value: 0x7f0b0002
			public const int postcode_from_gps = 2131427330;
			
			// aapt resource value: 0x7f0b000a
			public const int rating = 2131427338;
			
			// aapt resource value: 0x7f0b0000
			public const int subtitle = 2131427328;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int rating_bar_max_rating = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DialogProgressBarView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int InsertLocation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ListOfRestaurants = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ListOfRestaurantsListItem = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090006
			public const int dialog_data_download_failed_message = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int dialog_data_download_failed_negative_text = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int dialog_data_download_failed_positive_text = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int dialog_enable_location_message = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int dialog_enable_location_negative_text = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int dialog_enable_location_positive_text = 2131296266;
			
			// aapt resource value: 0x7f090002
			public const int insert_location_edit_text_hint = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int insert_location_find_takeaways = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int insert_location_subtitle_text = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int insert_location_title = 2131296256;
			
			// aapt resource value: 0x7f090004
			public const int insert_location_warning_empty = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int insert_location_warning_invalid = 2131296261;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int AppTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int InserPostcodeActionButton = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int ProgressDialogStyle = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int SplashScreen = 2131361793;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DisplayRating = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int DisplayRating_maxRating = 0;
			
			// aapt resource value: 1
			public const int DisplayRating_rating = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
